# Generated by Django 3.2.5 on 2021-07-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='cars',
        ),
        migrations.AddField(
            model_name='cars',
            name='configCab',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dash.cabineplane'),
            preserve_default=False,
        ),
    ]
