# Generated by Django 3.2.9 on 2022-04-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeytarif',
            name='taxe',
            field=models.FloatField(default=0.0, verbose_name='taxe'),
        ),
        migrations.AlterField(
            model_name='journeytarif',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='actif_tarif'),
        ),
    ]
