# Generated by Django 3.2.9 on 2022-04-07 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20220407_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='dash.covercity', verbose_name='Current CoverCity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routing',
            name='whereFrom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='predecessor', to='dash.routing', verbose_name='where from'),
        ),
        migrations.AlterField(
            model_name='routing',
            name='whereTo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='successor', to='dash.routing', verbose_name='where to'),
        ),
    ]
