# Generated by Django 3.2.5 on 2021-07-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dash', '0002_auto_20210729_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabineplane',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cabine_plane', to='account.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pompany_cars', to='account.company'),
            preserve_default=False,
        ),
    ]
