# Generated by Django 3.2.9 on 2022-04-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20220408_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='routes',
        ),
        migrations.AddField(
            model_name='journey',
            name='route',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='routing_journies', to='dash.routing', verbose_name='routing'),
        ),
    ]
