# Generated by Django 3.2.5 on 2021-07-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20210729_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabineplane',
            name='devMod',
            field=models.BooleanField(default=False),
        ),
    ]
