# Generated by Django 3.2.5 on 2021-07-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_cabineplane_devmod'),
    ]

    operations = [
        migrations.AddField(
            model_name='covercity',
            name='code',
            field=models.CharField(max_length=200, null=True, verbose_name='code'),
        ),
    ]
