# Generated by Django 3.2.9 on 2022-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20220412_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='covercity',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='picture of city'),
        ),
    ]
