# Generated by Django 3.2.5 on 2021-07-29 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_covercity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='idConfigCab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='dash.cabineplane'),
        ),
    ]
