# Generated by Django 3.2.9 on 2022-07-12 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20220713_0128'),
        ('dash', '0006_alter_journeytarif_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OP', 'In Option'), ('ES', 'Emis'), ('NS', 'No-show'), ('VD', 'Voided'), ('FN', 'Flown')], default='OP', help_text='status of ticked', max_length=5, verbose_name='status')),
                ('n_ticket', models.IntegerField(unique=True, verbose_name='number of ticket')),
                ('n_coupons', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='number of coupons')),
                ('passenger', models.OneToOneField(help_text='the passenger to have this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='passenger_ticket', to='clients.passenger', verbose_name='passenger')),
            ],
            options={
                'verbose_name': 'Billets',
                'db_table': 'tb_tickets',
            },
        ),
    ]
