# Generated by Django 3.2.5 on 2021-08-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_seat_idconfigcab'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='devise',
            field=models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=5, verbose_name='money devise'),
        ),
    ]
