# Generated by Django 3.2.3 on 2021-11-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_journey_devise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabineplane',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='cabineplane',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='covercity',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='covercity',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='journey',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='journey',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='pointofsale',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='pointofsale',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='pointofsaleworker',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='pointofsaleworker',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='routing',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='routing',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='data_updated',
            new_name='date_updated',
        ),
    ]
