# Generated by Django 3.2.9 on 2022-07-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Billet', 'verbose_name_plural': 'Billets'},
        ),
    ]
