# Generated by Django 3.2.9 on 2022-07-31 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='orgine',
            field=models.ForeignKey(default=None, help_text='the orgin of routing(first town)', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.routing', verbose_name='orgine'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='devise',
            field=models.CharField(choices=[('USD', 'Dollars'), ('DCF', 'Franc congolais')], default='DCF', help_text='the kind of money', max_length=5, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=0.0, help_text='the price of thing', verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='journeytarif',
            name='devise',
            field=models.CharField(choices=[('USD', 'Dollars'), ('DCF', 'Franc congolais')], default='DCF', help_text='the kind of money', max_length=5, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
