# Generated by Django 3.2.9 on 2021-11-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20211106_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='routing',
        ),
        migrations.CreateModel(
            name='RouteJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(verbose_name='price')),
                ('devise', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=5, verbose_name='money devise')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_routes', to='dash.journey', verbose_name='journey')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='dash.routing', verbose_name='routes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='journey',
            name='routes',
            field=models.ManyToManyField(through='dash.RouteJourney', to='dash.Routing'),
        ),
    ]
