# Generated by Django 3.2.9 on 2021-11-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_auto_20211124_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='routes',
            field=models.ManyToManyField(related_name='routing_journies', through='dash.RouteJourney', to='dash.Routing', verbose_name='routing'),
        ),
    ]
