# Generated by Django 3.2.9 on 2022-09-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_auto_20220731_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routing',
            name='orgine',
        ),
        migrations.AddField(
            model_name='routing',
            name='origin',
            field=models.ForeignKey(default=None, help_text='the orgin of routing(first town)', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.routing', verbose_name='origin'),
        ),
    ]
