# Generated by Django 3.2.9 on 2022-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_auto_20220908_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeytarif',
            name='devise',
            field=models.CharField(choices=[('USD', 'Dollars'), ('CDF', 'Franc congolais')], default='CDF', max_length=10),
        ),
    ]
