# Generated by Django 3.2.9 on 2021-11-26 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_journey_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routing',
            name='whreTo',
        ),
        migrations.AddField(
            model_name='routing',
            name='whereTo',
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.CASCADE, related_name='whereTo', to='dash.covercity', verbose_name='where to'),
            preserve_default=False,
        ),
    ]
