# Generated by Django 3.2.9 on 2022-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_routing_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='etat',
            field=models.CharField(choices=[('OP', 'Operationnel'), ('NO', 'Non operationnel'), ('HS', 'Hors service')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(choices=[('SEAT', 'seating'), ('SPACE', 'space or  couloir')], default='SEAT', max_length=10, verbose_name='type'),
        ),
    ]
