# Generated by Django 3.2.9 on 2022-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_auto_20220325_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='distance',
            field=models.FloatField(default=0.0, verbose_name='distance(Km)'),
        ),
    ]
