# Generated by Django 3.2.9 on 2022-03-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_routing_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='price',
        ),
    ]
