# Generated by Django 3.2.9 on 2022-03-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211106_1217'),
        ('clients', '0019_alter_placereserved_journey'),
        ('dash', '0014_auto_20220330_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, verbose_name='code_class')),
                ('name', models.CharField(max_length=10, verbose_name='name_class')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_class', to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JourneyTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('devise', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=5, verbose_name='money devise')),
                ('adult', models.FloatField(default=0.0, verbose_name='tarif_adult')),
                ('child', models.FloatField(default=0.0, verbose_name='tarif_child')),
                ('baby', models.FloatField(default=0.0, verbose_name='tarif_baby')),
                ('actif', models.BooleanField(default=0.0, verbose_name='actif_tarif')),
                ('journey_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif', to='dash.journeyclass')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='dash.routing', verbose_name='routes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='journey',
            name='routes',
            field=models.ManyToManyField(related_name='routing_journies', to='dash.Routing', verbose_name='routing'),
        ),
        migrations.DeleteModel(
            name='RouteJourney',
        ),
    ]
