# Generated by Django 3.2.9 on 2022-06-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='type_employe',
            field=models.CharField(choices=[('DG', 'Directeur General'), ('DC', 'Directeur Commercial'), ('DT', 'Directeur Techniques'), ('DO', 'Directeur Operations'), ('SP', 'Superviseur Technique'), ('AT', 'Agent Technique'), ('SC', 'Superviseur Commercial'), ('AC', 'Agent commercial'), ('AV', 'Agent de vente'), ('AOV', 'Autre Agent vente'), ('SO', 'Superviseur des operations'), ('AO', 'Agent des operation')], default='AOV', max_length=5),
            preserve_default=False,
        ),
    ]
