# Generated by Django 3.2.9 on 2022-03-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyClientFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=200, unique=True, verbose_name='number folder')),
                ('session', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='session')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='account.client', verbose_name='client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JourneySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='key session folder')),
                ('dateExpiration', models.DateTimeField(verbose_name='expiration date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('birthDay', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Woman'), ('H', 'Man'), ('I', 'Indeterminate')], max_length=10, verbose_name='gender')),
                ('typeUser', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('baby', 'Baby')], max_length=20, verbose_name='type of user')),
            ],
            options={
                'ordering': ['firstname'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeletectedJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('numberAdult', models.IntegerField(default=1, verbose_name='number of adult')),
                ('numberChild', models.IntegerField(default=0, verbose_name='number of child')),
                ('numberBaby', models.IntegerField(default=0, verbose_name='number of baby')),
                ('last_step', models.IntegerField(default=1, verbose_name='the last step')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_journey_selected', to='clients.journeyclientfolder', verbose_name='folder')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_selected', to='dash.journey', verbose_name='journey')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_journey_selected', to='clients.journeysession', verbose_name='session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(default='CASH', help_text='provider determine the mode of payment', max_length=200, verbose_name='provider')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmation')),
                ('costTotal', models.CharField(max_length=200, null=True)),
                ('date_payment', models.DateTimeField(null=True)),
                ('journey_selected', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='clients.seletectedjourney', verbose_name='voyage selectionner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceReserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False, verbose_name='expiration')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_seats_reserved', to='dash.routing', verbose_name='routes journey')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='clients.passenger', verbose_name='passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reseved', to='dash.seat', verbose_name='seat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='passenger',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='clients.seletectedjourney', verbose_name='journey'),
        ),
        migrations.CreateModel(
            name='OtherInfoReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('birthDay', models.DateField()),
                ('email', models.EmailField(max_length=200, verbose_name='nom')),
                ('num_tel', models.CharField(max_length=200, verbose_name='nom')),
                ('num_tel_emergency', models.CharField(max_length=200, verbose_name='nom')),
                ('gender', models.CharField(choices=[('F', 'Woman'), ('H', 'Man'), ('I', 'Indeterminate')], max_length=10, verbose_name='gender')),
                ('degre_parent', models.CharField(help_text='degre of responsable of reservation', max_length=200, verbose_name='degre of parent')),
                ('piece_id', models.CharField(max_length=200, verbose_name='nom')),
                ('num_piece_id', models.CharField(max_length=200, verbose_name='nom')),
                ('adress_from', models.CharField(max_length=250, verbose_name='nom')),
                ('adress_to', models.CharField(max_length=250, verbose_name='nom')),
                ('journey', models.OneToOneField(help_text='the selected journey reservations', on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='clients.seletectedjourney', verbose_name='reservations')),
            ],
            options={
                'ordering': ['firstname'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FretPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('poid', models.IntegerField(verbose_name='poids')),
                ('volume', models.IntegerField(verbose_name='volume')),
                ('code', models.CharField(max_length=50, verbose_name='code of fret')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frets', to='clients.passenger', verbose_name='passenger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
