# Generated by Django 3.2.5 on 2021-07-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyClientFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=200, unique=True, verbose_name='number folder')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='account.client', verbose_name='client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JourneySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='key session folder')),
                ('dateExpiration', models.DateTimeField(verbose_name='expiration date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('birthDay', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Woman'), ('H', 'Man'), ('I', 'Indeterminate')], max_length=10, verbose_name='gender')),
                ('typeUser', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Baby', 'Baby')], max_length=20, verbose_name='type of user')),
            ],
            options={
                'ordering': ['firstname'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeletectedJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('numberAdult', models.IntegerField(verbose_name='number of adult')),
                ('numberChild', models.IntegerField(verbose_name='number of child')),
                ('numberBaby', models.IntegerField(verbose_name='number of baby')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_journey_selected', to='clients.journeyclientfolder', verbose_name='folder')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_selected', to='dash.journey', verbose_name='journey')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_journey_selected', to='clients.journeysession', verbose_name='session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceReserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False, verbose_name='expiration')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='clients.passenger', verbose_name='passenger')),
                ('routing', models.ManyToManyField(related_name='seats_on_route', to='dash.Routing', verbose_name='routing')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reseved', to='dash.seat', verbose_name='seat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='passenger',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='clients.seletectedjourney', verbose_name='journey'),
        ),
        migrations.CreateModel(
            name='FretPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('poid', models.IntegerField(verbose_name='poids')),
                ('volume', models.IntegerField(verbose_name='volume')),
                ('code', models.CharField(max_length=50, verbose_name='code of fret')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frets', to='clients.passenger', verbose_name='passenger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
