# Generated by Django 3.2.5 on 2021-08-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='typeUser',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('baby', 'Baby')], max_length=20, verbose_name='type of user'),
        ),
    ]
