# Generated by Django 3.2.9 on 2022-04-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seletectedjourney',
            old_name='numberAdult',
            new_name='adult',
        ),
        migrations.RenameField(
            model_name='seletectedjourney',
            old_name='numberBaby',
            new_name='baby',
        ),
        migrations.RenameField(
            model_name='seletectedjourney',
            old_name='numberChild',
            new_name='child',
        ),
        migrations.RemoveField(
            model_name='seletectedjourney',
            name='last_step',
        ),
    ]
