# Generated by Django 3.2.5 on 2021-08-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_passenger_typeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyclientfolder',
            name='session',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='session'),
        ),
    ]
