# Generated by Django 3.2.9 on 2022-04-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220412_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeysession',
            old_name='dateExpiration',
            new_name='date_expiration',
        ),
    ]
