# Generated by Django 3.2.5 on 2021-08-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_journeyclientfolder_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='seletectedjourney',
            name='last_step',
            field=models.IntegerField(default=1, verbose_name='the last step'),
        ),
        migrations.AlterField(
            model_name='seletectedjourney',
            name='numberAdult',
            field=models.IntegerField(default=1, verbose_name='number of adult'),
        ),
        migrations.AlterField(
            model_name='seletectedjourney',
            name='numberBaby',
            field=models.IntegerField(default=0, verbose_name='number of baby'),
        ),
        migrations.AlterField(
            model_name='seletectedjourney',
            name='numberChild',
            field=models.IntegerField(default=0, verbose_name='number of child'),
        ),
    ]
