# Generated by Django 3.2.5 on 2021-08-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company_description'),
        ('clients', '0004_auto_20210817_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyclientfolder',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='account.client', verbose_name='client'),
        ),
    ]
