# Generated by Django 3.2.5 on 2021-08-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_journeyclientfolder_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyclientfolder',
            name='session',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='session'),
        ),
    ]
