# Generated by Django 3.2.9 on 2022-05-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dash', '0005_covercity_image'),
        ('clients', '0006_seletectedjourney_journey_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherinforeservation',
            name='adress_from',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='adress_from'),
        ),
        migrations.AlterField(
            model_name='otherinforeservation',
            name='adress_to',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='adress_to'),
        ),
        migrations.AlterField(
            model_name='otherinforeservation',
            name='degre_parent',
            field=models.CharField(blank=True, help_text='degre of responsable of reservation', max_length=200, null=True, verbose_name='degre of parent'),
        ),
        migrations.AlterField(
            model_name='otherinforeservation',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Woman'), ('H', 'Man'), ('I', 'Indeterminate')], max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='otherinforeservation',
            name='num_piece_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='num_piece_id'),
        ),
        migrations.AlterField(
            model_name='otherinforeservation',
            name='piece_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='piece_id'),
        ),
        migrations.AlterField(
            model_name='seletectedjourney',
            name='state',
            field=models.CharField(choices=[('OPTION', 'in option'), ('CORFIMED', 'confirme'), ('CANCELED', 'annule'), ('RESERVED', 'reserve')], default='OPTION', max_length=20, verbose_name='status reservation'),
        ),
        migrations.CreateModel(
            name='ResearchReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('adult', models.IntegerField(default=1, verbose_name='number of adult')),
                ('child', models.IntegerField(default=0, verbose_name='number of child')),
                ('baby', models.IntegerField(default=0, verbose_name='number of baby')),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.client')),
                ('journey_class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.journeyclass', verbose_name="journe's class")),
                ('whereFrom', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recherche_route_whereFrom', to='dash.routing', verbose_name='where from')),
                ('whereTo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recherche_route_whereTo', to='dash.routing', verbose_name='where to')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
