# Generated by Django 3.2.5 on 2021-08-17 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_seat_idconfigcab'),
        ('clients', '0006_alter_journeyclientfolder_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereserved',
            name='journey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='journey_seats', to='dash.journey', verbose_name='journey'),
            preserve_default=False,
        ),
    ]
