# Generated by Django 3.2.9 on 2022-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20220520_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreservation',
            name='dateDepart',
            field=models.DateField(default='2022-05-20', verbose_name='Departure Date'),
            preserve_default=False,
        ),
    ]
