# Generated by Django 3.2.3 on 2021-11-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_placereserved_journey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fretpassenger',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='fretpassenger',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='journeyclientfolder',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='journeyclientfolder',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='journeysession',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='journeysession',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='placereserved',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='placereserved',
            old_name='data_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='seletectedjourney',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='seletectedjourney',
            old_name='data_updated',
            new_name='date_updated',
        ),
    ]
