# Generated by Django 3.2.9 on 2022-05-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dash', '0005_covercity_image'),
        ('clients', '0008_researchreservation_datedepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreservation',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.client'),
        ),
        migrations.AlterField(
            model_name='researchreservation',
            name='journey_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.journeyclass', verbose_name="journe's class"),
        ),
        migrations.AlterField(
            model_name='researchreservation',
            name='whereFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recherche_route_whereFrom', to='dash.routing', verbose_name='where from'),
        ),
        migrations.AlterField(
            model_name='researchreservation',
            name='whereTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recherche_route_whereTo', to='dash.routing', verbose_name='where to'),
        ),
    ]
