# Generated by Django 3.2.9 on 2021-11-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20211106_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seletectedjourney',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_journey_selected', to='clients.journeysession', unique=True, verbose_name='session'),
        ),
    ]
