# Generated by Django 3.2.9 on 2021-11-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_auto_20211124_1916'),
        ('clients', '0009_alter_seletectedjourney_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereserved',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_seats', to='dash.routejourney', verbose_name='routes journey'),
        ),
    ]
