# Generated by Django 3.2.9 on 2022-05-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_covercity_image'),
        ('clients', '0009_auto_20220520_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreservation',
            name='whereFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recherche_route_whereFrom', to='dash.covercity', verbose_name='where from'),
        ),
        migrations.AlterField(
            model_name='researchreservation',
            name='whereTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recherche_route_whereTo', to='dash.covercity', verbose_name='where to'),
        ),
    ]
