# Generated by Django 3.2.9 on 2021-11-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_seletectedjourney_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(default='CASH', help_text='provider determine the mode of payment', max_length=200, verbose_name='provider')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmation')),
                ('costTotal', models.CharField(max_length=200, null=True)),
                ('date_payment', models.DateTimeField(null=True)),
                ('journey_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='clients.seletectedjourney', verbose_name='voyage selectionner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
