# Generated by Django 3.2.9 on 2022-06-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20220603_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JourneyClientFolderMoreSerializer',
        ),
    ]
