# Generated by Django 3.2.9 on 2021-11-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_validationpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placereserved',
            old_name='routing',
            new_name='routes',
        ),
    ]
