# Generated by Django 3.2.9 on 2022-07-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_delete_journeyclientfoldermoreserializer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='typeUser',
            field=models.CharField(choices=[('AD', 'Adult'), ('CHD', 'Child'), ('INF', 'Baby')], default='AD', max_length=20, verbose_name='type of user'),
        ),
        migrations.AlterField(
            model_name='seletectedjourney',
            name='status',
            field=models.CharField(choices=[('OP', 'In option'), ('VD', 'Voided'), ('ES', 'Emis')], default='OP', max_length=20, verbose_name='status reservation'),
        ),
        migrations.DeleteModel(
            name='ValidationPayment',
        ),
    ]
