# Generated by Django 3.2.9 on 2021-11-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_journey_routes'),
        ('clients', '0013_rename_routing_placereserved_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereserved',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_seats_reserved', to='dash.routejourney', verbose_name='routes journey'),
        ),
    ]
