# Generated by Django 3.2.9 on 2021-11-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_placereserved_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placereserved',
            name='routes',
        ),
    ]
