# Generated by Django 3.2.9 on 2022-07-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20220713_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='seletectedjourney',
            name='pnr',
            field=models.CharField(max_length=7, null=True, unique=True, verbose_name='Passenger name record'),
        ),
    ]
