# Generated by Django 3.2.9 on 2021-11-26 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_placereserved_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfoReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('birthDay', models.DateField()),
                ('email', models.EmailField(max_length=200, verbose_name='nom')),
                ('num_tel', models.CharField(max_length=200, verbose_name='nom')),
                ('num_tel_emergency', models.CharField(max_length=200, verbose_name='nom')),
                ('gender', models.CharField(choices=[('F', 'Woman'), ('H', 'Man'), ('I', 'Indeterminate')], max_length=10, verbose_name='gender')),
                ('degre_parent', models.CharField(help_text='degre of responsable of reservation', max_length=200, verbose_name='degre of parent')),
                ('piece_id', models.CharField(max_length=200, verbose_name='nom')),
                ('num_piece_id', models.CharField(max_length=200, verbose_name='nom')),
                ('adress_from', models.CharField(max_length=250, verbose_name='nom')),
                ('adress_to', models.CharField(max_length=250, verbose_name='nom')),
                ('birth_date', models.DateField(verbose_name='nom')),
                ('journey', models.OneToOneField(help_text='the selected journey reservations', on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='clients.seletectedjourney', verbose_name='reservations')),
            ],
            options={
                'ordering': ['firstname'],
                'abstract': False,
            },
        ),
    ]
