# Generated by Django 3.2.9 on 2022-07-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_seletectedjourney_pnr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherinforeservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={},
        ),
    ]
