# Generated by Django 3.2.9 on 2022-07-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20220713_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherinforeservation',
            options={'ordering': ['firstname']},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['firstname']},
        ),
    ]
