# Generated by Django 3.2.9 on 2021-11-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_otherinforeservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationpayment',
            name='journey_selected',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='clients.seletectedjourney', verbose_name='voyage selectionner'),
        ),
    ]
