# Generated by Django 3.2.9 on 2022-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_auto_20220713_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherinforeservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={},
        ),
        migrations.AlterField(
            model_name='otherinforeservation',
            name='gender',
            field=models.CharField(choices=[('F', 'Woman'), ('H', 'Man'), ('I', 'Indeterminate')], default='I', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('F', 'Woman'), ('H', 'Man'), ('I', 'Indeterminate')], default='I', max_length=10, verbose_name='gender'),
        ),
    ]
