# Generated by Django 3.2.9 on 2022-03-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_auto_20220330_1620'),
        ('clients', '0018_remove_otherinforeservation_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereserved',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_seats_reserved', to='dash.routing', verbose_name='routes journey'),
        ),
    ]
