# Generated by Django 3.2.9 on 2022-11-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_auto_20221028_1047'),
        ('clients', '0020_sendticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('step', models.IntegerField(choices=[(1, 'SELECT_JOURNEY'), (2, 'PASSENGER'), (3, 'OTHER_INFO'), (4, 'COMPLETED')], default=1, max_length=2, verbose_name='step reservation')),
                ('status', models.CharField(choices=[('OP', 'In option'), ('VD', 'Voided'), ('ES', 'Emis')], default='OP', max_length=20, verbose_name='status reservation')),
                ('adult', models.IntegerField(default=1, verbose_name='number of adult')),
                ('child', models.IntegerField(default=0, verbose_name='number of child')),
                ('baby', models.IntegerField(default=0, verbose_name='number of baby')),
                ('pnr', models.CharField(max_length=7, null=True, unique=True, verbose_name='Passenger name record')),
                ('folder', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clients.journeyclientfolder', verbose_name='folder')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_selected', to='dash.journey', verbose_name='journey')),
                ('journey_class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dash.journeyclass', verbose_name="journe's class")),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_journey_selected', to='clients.journeysession', verbose_name='session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='otherinforeservation',
            name='journey',
            field=models.OneToOneField(help_text='the selected journey reservations', on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='clients.reservation', verbose_name='reservations'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='clients.reservation', verbose_name='journey'),
        ),
        migrations.AlterField(
            model_name='sendticket',
            name='journey',
            field=models.OneToOneField(help_text='the selected journey reservations', on_delete=django.db.models.deletion.CASCADE, related_name='send_ticket', to='clients.reservation', verbose_name='reservations'),
        ),
        migrations.DeleteModel(
            name='SeletectedJourney',
        ),
    ]
