# Generated by Django 3.2.9 on 2022-11-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_reservation_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='folder',
        ),
    ]
